# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67ae6381bbb21a0f4d6778ef2a87ea7803aa1906a8e5d358e2d3ac34b41dc99dd974f85374ce980c8fa12e35386f984f9a354bd8272bda9fcb4166829f9cd074

test:
  secret_key_base: f2450f1ff6de00270149a4e0a56ffdf23a31c103f37dbd9927fad8b1b2369ef08d3db05d13997321367d841d7455db0a3ad3cf7602218e6e4e52f1e78dadaef9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
